dist: xenial
language: python
python:
- 3.6.9
- '3.7'
install:
- pip install -r requirements.txt
script:
- "/bin/bash -c ci/run.sh"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: iHp9PSQdArDOpnvzgO4JSHQ5LRgYVmyJll1/dCj1UuMa6GuOGNigwSrRqc6LWDP2m329ECxfb5aDP5UnwmY8r0/2j1IqcUaQFWHzqx1j6Z5RUBccZOr59QIJs97hubSz8oiE4hPR09MRGBvFNiwYSl5vxNpKXm4/HkCZfv36uXdSwHNCRqPGHOLvjzUeHPWGvX13oIF76cDHFcHy6rt3RzIT9rsBp6A31PfTXonmZYtOWxMS0lh619p11TkHrz1wo+LpMzBmUZqhym8z2XsbWG9X3KnEFjvrKSE4xnzsxBXwT5/8yHfUZpuHwPxd7LFf+6Hp1vR/acwnCjTo92KALod1Y5X0tYhnJwjfIV3RJpjS3JHFqxAEdfMejUPVvDVZNhhmJkcIvVTBKlgZq/3dM4wUWn57ATYuWXTsDKLlH+/fqbUeWTX2miXMh7o/NBSgS0U9Q9JphPTLZuFNaJ2YgErt8f26SyZVWwgfA48IMaaV4vb37eS7aubZWaSXAw8MCSFwfkxrhUHM9uwNfXnS+m4urNCOFJgNiE0D3EixStD5S1fE9NnbnmBNZUVUm8Unpm6KvSEnuIvMoH0epQipEEKTcKfaNxgx1k6PyRXPkxLLLRluMxirnUKRnuso2tSChbc46pl5hqaAA5nlG9DOL/xwW6yZvyPZ751PPOeOXq4=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
  branches:
    only:
    - master
